version: 2
updates:
  # Uppdatera GitHub Actions som används i dina workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Om du har en Dockerfil för att bygga en container
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
